from __future__ import annotations

from typing import Iterable, Optional
from uuid import UUID

from sqlalchemy.orm import Session

from api.models import Candidate, Job, JobApplicant, JobCandidateRanking


def refresh_candidate_best_job_cache(db: Session, candidate_ids: Iterable[UUID]) -> None:
    """
    Recompute Candidate.best_job_match_score / best_job_external_id from persisted
    JobCandidateRanking rows, restricted to jobs the candidate actually applied to.

    Per spec: "Show BEST MATCH job: highest score, only among jobs candidate applied to."
    cross_encoder_score is stored on a 0–1 scale; best_job_match_score is on a 0–100 scale.
    """
    ids = [cid for cid in candidate_ids if cid]
    if not ids:
        return

    # Only consider jobs where the candidate has a JobApplicant row (applied or recruiter-added).
    rows = (
        db.query(JobCandidateRanking.candidate_id, Job.external_id, JobCandidateRanking.cross_encoder_score)
        .join(Job, Job.id == JobCandidateRanking.job_id)
        .join(JobApplicant, (JobApplicant.job_id == JobCandidateRanking.job_id) & (JobApplicant.candidate_id == JobCandidateRanking.candidate_id))
        .filter(JobCandidateRanking.candidate_id.in_(ids))
        .all()
    )
    best_score: dict[UUID, float] = {}
    best_job_ext: dict[UUID, str] = {}
    for cid, ext, raw in rows:
        try:
            s01 = float(raw or 0.0)
        except Exception:
            s01 = 0.0
        s100 = max(0.0, min(100.0, s01 * 100.0))
        cur = best_score.get(cid, -1.0)
        if s100 > cur:
            best_score[cid] = s100
            best_job_ext[cid] = (ext or "").strip()

    for cid in ids:
        if cid in best_score:
            db.query(Candidate).filter(Candidate.id == cid).update(
                {
                    Candidate.best_job_match_score: float(best_score[cid]),
                    Candidate.best_job_external_id: best_job_ext.get(cid, "") or "",
                },
                synchronize_session=False,
            )
        else:
            db.query(Candidate).filter(Candidate.id == cid).update(
                {Candidate.best_job_match_score: None, Candidate.best_job_external_id: ""},
                synchronize_session=False,
            )

    db.commit()


def workspace_best_scores(
    db: Session,
    workspace_id: UUID,
    candidate_ids: list[UUID],
) -> dict[UUID, tuple[float, str]]:
    """
    Return the best cross-encoder score (0–100 scale) and corresponding
    job external_id for each candidate, considering ONLY rankings that were
    produced by the given recruiter workspace.

    This ensures recruiters never see scores generated by a different
    recruiter's matching run against a different recruiter's jobs.

    Returns {candidate_id: (best_score_0_100, best_job_external_id)}.
    Missing candidates (no rankings for this workspace) are absent from
    the returned dict — callers should treat absence as no score yet.
    """
    if not candidate_ids or workspace_id is None:
        return {}

    rows = (
        db.query(JobCandidateRanking.candidate_id, Job.external_id, JobCandidateRanking.cross_encoder_score)
        .join(Job, Job.id == JobCandidateRanking.job_id)
        .filter(
            JobCandidateRanking.workspace_id == workspace_id,
            JobCandidateRanking.candidate_id.in_(candidate_ids),
        )
        .all()
    )

    best: dict[UUID, tuple[float, str]] = {}
    for cid, ext, raw in rows:
        s = max(0.0, min(100.0, float(raw or 0.0) * 100.0))
        prev_score = best[cid][0] if cid in best else -1.0
        if s > prev_score:
            best[cid] = (s, (ext or "").strip())

    return best
